version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /opt/db:/data/db
  node:
    image: tst-node
    ports:
      - 5000:80
    links:
      - mongo

  